geoapps/em1d_inversion.py, geoapps/inversion.py, geoapps/pf_inversion.py
A reference to `mvic' was present after the assert statement would have failed. Different references to mvi or magnetics or mvic in different places: sometimes three types being set as vector mag (mvi, magnetics, mvic), and sometime two types (mvi, magnetics).
I streamlined all the calls with: magnetics( = magsus), mvi (spherical), and mvic (cartesian), and eliminated mag. I think you were using magnetics to mean MVIC, but I thought it made sense to clarify which was a vector and which wasn't.
=> Fix inconsistencies in magnetic inversion types. 

.github/workflows/pytest-unix-os.yaml, .github/workflows/pytest-windows.yaml
**GEOPY-177 - python version not used in github actions** 
so that they appear as two different jobs in PR required conditions
=> GEOPY-177: add platform to pytest job

docs/content/installation.rst
**GEOPY-98 - Python 3.6.X not supported with pip install** 
Needed for docs.
=> Change reference to python 3.7

.github/workflows/pytest-unix-os.yaml, .pre-commit-config.yaml
**GEOPY-258 - change required test platforms per branch** 
fixup for https://github.com/MiraGeoscience/geoapps/pull/108
relates to https://github.com/MiraGeoscience/geoh5py/pull/104
=> GEOPY-258: fixup github workfow file for Unix

geoapps/io/input_file.py
**GEOPY-296 - some typos in doc**
=> GEOPY-296: remove one usage of GA abbreviation in doc

geoapps/drivers/pf_inversion.py, geoapps/simpegPF/Directives.py
`SaveOutputEveryIteration` output directive was commented out of PF inversion code, likely to avoid a bug in the output formatting. This fixes the bug and enables the directive again.
=> Re-enable output of PF Inversion iteration convergence progress

.coveragerc
**GEOPY-334 - exclude simpegEM1D and simpegPF from test coverage**
=> GEOPY-334: exclude simpegEM1D and simpegPF from test coverage

.pre-commit-config.yaml, devtools/conda_env_pylint.bat
**GEOPY-358 - use local editable geoh5 in geoapps dev environment**
=> GEOPY-358: followup: fix running pylint from precommit

geoapps/drivers/base_inversion.py
**GEOPY-395 - save_misfit is not working for multi-component inversions**
Previously merged into dev, but is flagged for 0.6.1 release.
=> GEOPY-395: Remove finish_inversion_method from base driver.

geoapps/io/__init__.py, tests/write_default_uijson_test.py
hotfix to get rid of a warning encountered during demo practise
=> move write_default_uijson out of import in init to remove runtimewarning

geoapps/inversion/constants.py
**GEOPY-458 - Allow both "Vertex" and "Cell" values for "topography"**
=> GEOPY-458: Allow both "Vertex" and "Cell" values for "topography"

.github/workflows/create_env_file.yml, .github/workflows/pytest-windows.yaml, .github/workflows/static-analysis.yml, Install_or_Update.bat, devtools/create_application_env_files.py, devtools/setup-dev.bat
**GEOPY-682 - geoapps 0.9.0 yml file for analyst simpeg fails to install**
no strong reason for moving to 3.10
Anaconda and Miniconda are still using 3.9 for the base environment
=> GEOPY-682: back to Python 3.9 for installation

geoapps/driver_base/driver.py, tests/run_tests/octree_creation_test.py, tests/run_tests/peak_finder_test.py
**GEOPY-732 - Workspace closed on ui.json execution of non-inversion apps**
cherry-picked from https://github.com/MiraGeoscience/geoapps/pull/464
Conflicts:
-	geoapps/driver_base/driver.py
=> GEOPY-732: Workspace closed on ui.json execution of non-inversion apps [cherry-pick for 0.9.2] 

.github/workflows/create_env_file.yml, Install_or_Update.bat, devtools/setup-dev.bat
**GEOPY-824 - use Python 3.10 as default run environment**
=> GEOPY-824: use Python 3.10 as default runtime environment

.github/workflows/pytest-unix-os.yaml, .github/workflows/pytest-windows.yaml, .github/workflows/static-analysis.yml
**GEOPY-834 - kill running github actions upon new commit**
Same changes as in https://github.com/MiraGeoscience/geoh5py/pull/285
=> GEOPY-834: kill running github actions the same PR

devtools/create_application_env_files.py
**GEOPY-824 - use Python 3.10 as default run environment**
fix Python version to 3.10 in the generated environment file for the application
=> GEOPY-824: create the application env file for Python 3.10 - fixup

Install_or_Update.bat, devtools/setup-conda-base.bat, devtools/setup-dev.bat
**GEOPY-888 - libmamba in install script makes the installation stall for some configuration**
libmamba is a faster solver for conda, but seems to fail depending  on the conda installation
(To learn more about libmamba solver:  [A Faster Solver for Conda: Libmamba](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community) )
=> GEOPY-888: do not enforce libmamba as conda solver

Start_applications.bat
**GEOPY-912 - start_notebook script not found in some instances**
Do not assume `start_notebook` script is in path.
When installing geoapps, start_notebook is supposed to be exposed as an executable script in the environment. It seems not be the case sometimes. Just call the python module directly instead.
=> GEOPY-912: start_notebook script not found in some instances

conda-py-3.10-lock.yml, conda-py-3.9-lock.yml, devtools/add_url_tag_sha256.py, environments/conda-py-3.10-linux-64-dev.lock.yml, environments/conda-py-3.10-linux-64.lock.yml, environments/conda-py-3.10-osx-64-dev.lock.yml, environments/conda-py-3.10-osx-64.lock.yml, environments/conda-py-3.10-win-64-dev.lock.yml, environments/conda-py-3.10-win-64.lock.yml, environments/conda-py-3.9-linux-64-dev.lock.yml, environments/conda-py-3.9-linux-64.lock.yml, environments/conda-py-3.9-osx-64-dev.lock.yml, environments/conda-py-3.9-osx-64.lock.yml, environments/conda-py-3.9-win-64.lock.yml
**GEOPY-937 - lock files still pointing to mira-omf 3.0.0-rc3 instead of rc.4**
=> GEOPY-937: update lock files to pointing to mira-omf 3.0.0-rc.4

geoapps/inversion/electromagnetics/time_domain/constants.py
**GEOPY-1113 - Remove disk storage option to TEM inversion until fix is found**
=> GEOPY-1113: Limit sensitivity storage to RAM on tem inversion

docs/content/release_notes.rst
**GEOPY-1203 - Fix docs of release v0.11.0**
=> GEOPY-1203

geoapps/clustering/driver.py
**GEOPY-1245 - Clustering: Group IDs in application don't match output**
The issue cames from the order of the cluster, which was random even if the seed was fixed. ordering the ids of the clusters based on their values fix the issue.
=> GEOPY-1245 - update kmeans to ensure the clusters are always the same.

Install_or_Update.bat, README.rst, devtools/setup-dev.bat
**GEOPY-1445 - apply latest version of python-conda-template to geoapps**
also requires newer version of Conda which accepts "-y" option instead of "--force"
Applying same changes as in the template repo: https://github.com/MiraGeoscience/python-conda-template/pull/21
=> GEOPY-1445: force libmamba solver

pyproject.toml
**GEOPY-1712 - disable RUF005 as it is wrong with numpy array**
=> GEOPY-1712: Exclude RUF005 flag

.github/workflows/issue_to_jira.yml, .github/workflows/pr_add_jira_summary.yml, .github/workflows/python_analysis.yml
**DEVOPS-466 - rename python_ver input variable for consistency**
⚠️ Don't merge!
=> DEVOPS-466: Update input variable in shared workflows
