- geoapps/pf_inversion.py
Addresses issues #4 and #5 
- Implement the target misfit value selected in the application
- Fix major bug with the replication of norms for vector inversion.
Big thanks to @alexeytsv for catching those.
> Pf inversion update

- geoapps/__init__.py
- geoapps/inversion.py
- geoapps/pf_inversion.py
- geoapps/simpegPF/Directives.py
- geoapps/simpegPF/Regularization.py
- setup.py
Improve inversion with fixes to regularization, optimization and directives.
> Inv update

- docs/conf.py
- environment.yml
- geoapps/base.py
> Attempt a new theme to fix plotly output

- docs/content/apps/export.rst
- geoapps/base.py
- geoapps/export.py
- geoapps/inversion.py
- geoapps/pf_inversion.py
- geoapps/processing/data_interpolation.py
- geoapps/simpegPF/Directives.py
Various updates to applications:
1- Fix issues with Interpolation mesh creation and change of workspace
2- Address Issue #19 
3- Options for air cell fill value as requested in #8
> Inverse updates

- docs/content/apps/calculator.rst
- docs/content/apps/cdi_surface.rst
- docs/content/apps/contouring.rst
- docs/content/apps/coordinate_transformation.rst
- docs/content/apps/data_interpolation.rst
- docs/content/apps/edge_detection.rst
- docs/content/apps/export.rst
- docs/content/apps/geophysical_inversion.rst
- docs/content/apps/kmeans_clustering.rst
- docs/content/apps/lower_level.rst
- docs/content/apps/scatter_plots.rst
- geoapps/inversion.py
- geoapps/processing/data_interpolation.py
- Attempt to reduce build time
- Minor bug fixes
> Docs fixes

- docs/conf.py
- docs/content/apps/kmeans_clustering.rst
- docs/content/apps/lower_level.rst
- docs/index.rst
- geoapps/__init__.py
- geoapps/plotting/scatter.py
- geoapps/processing/clustering.py
- geoapps/utils/utils.py
- setup.py
Release 0.2.5
- Add bounds on kmeans histogram
- Fix docs
> Kmeans update

- docs/conf.py
- geoapps/__init__.py
- geoapps/processing/clustering.py
- geoapps/selection.py
- setup.py
> Patch 0 2 6

- .github/workflows/workflow.yaml
- .travis.yml
- docs/conf.py
- geoapps/__init__.py
- geoapps/processing/clustering.py
- geoapps/processing/data_interpolation.py
- geoapps/selection.py
- requirements_dev.txt
- setup.py
- tests/clustering_test.py
- Fix issues flagged by Daniel Brake @ Boliden
- Tackle issue #37 
- Start adding unit tests
> Clustering update

- .github/workflows/pr_add_jira_summary.yml
**GEOPY-176 - on geoapps PR automatically add JIRA issue summary from JIRA number**
> GEOPY-176: automatically add JIRA issue summary to PR

- .github/workflows/pytest-unix-os.yaml
- .github/workflows/pytest-windows.yaml
- environment.yml
- geoapps/__init__.py
- geoapps/base.py
- geoapps/inversion.py
- geoapps/plotting/plotting.py
- geoapps/processing/coordinate_transformation.py
- geoapps/processing/create.py
- geoapps/processing/edge_detection.py
- geoapps/selection.py
**GEOPY-177 - python version not used in github actions**
> GEOPY-177: fix matrix variable name for python version

- .github/workflows/pytest-windows.yaml
- assets/input.ui.json
- environment.yml
- geoapps/inversion.py
- geoapps/mt_inversion.py
**GEOPY-184 - POC with MT inversion for AMD** 
Run an ZTEM forward and inversion from ui.json.
To be completed with param validators.
> Add proof of concept for MT inversion with ui.json

- geoapps/base.py
- geoapps/create/contours.py
- geoapps/create/isosurface.py
- geoapps/create/surface_2d.py
- geoapps/processing/edge_detection.py
- geoapps/utils/formatters.py
- tests/formatters_test.py
Remove special characters by default from name of new objects. 
Defaults to replacing "." to "_"
> GEOPY-167 Add string_name formatter utils

- geoapps/io/input_file.py
- geoapps/io/params.py
**GEOPY-197 - Create models class to handle referencee and starting model loading, interpolation into inversion mesh** 
- add init from dict
- add write ui from params class
- stringfy uuid
> Patch io for load from dict

- .github/workflows/pytest-unix-os.yaml
- .github/workflows/pytest-windows.yaml
**GEOPY-258 - change required test platforms per branch** 
related to https://github.com/MiraGeoscience/geoh5py/pull/102
> GEOPY-258: change required test platforms per branch

- docs/content/applications/base_application.ipynb
- docs/content/applications/calculator.ipynb
- docs/content/applications/clustering.ipynb
- docs/content/applications/contouring.ipynb
- docs/content/applications/coordinate_transformation.ipynb
- docs/content/applications/create_octree.ipynb
- docs/content/applications/edge_detection.ipynb
- docs/content/applications/export.ipynb
- docs/content/applications/geophysical_inversion.ipynb
- docs/content/applications/peak_finder.ipynb
- docs/content/applications/scatter.ipynb
- docs/content/applications/view_selection.ipynb
- geoapps/applications/Create_contours.ipynb
- geoapps/applications/Edge_Detection.ipynb
- geoapps/applications/Index.ipynb
- geoapps/base.py
- geoapps/create/contours.py
- geoapps/processing/edge_detection.py
- geoapps/simulation.py
Replaced some standalone ANALYST references to Geoscience ANALYST.  Changed "export to GA" button names to just Export since full name was too long.
> GEOPY-165 Fixing up Geoscience ANALYST product name usages.

- geoapps/create/octree_mesh.py
> GEOPY-296: typo in octree_mesh.py doc

- .github/workflows/pytest-unix-os.yaml
- .github/workflows/static-analysis.yml
- .gitignore
- .pre-commit-config.yaml
- dev-extra-requirements.txt
- devtools/setup-dev.bat
- pylintrc
**GEOPY-297 - precommit in precommit-ci instead of github action** 
cherry pick of the merge commits for #127 and #128
> GEOPY-297:  precommit in precommit-ci instead of github action

- assets/uijson/direct_current_forward.ui.json
- assets/uijson/direct_current_inversion.ui.json
**GEOPY-371 - Review: DC** 
Adding ui.json files for dc fwd/inv
> Add ui.json files to assets

- environment.yml
**GEOPY-332 - Release geoapps 0.6.0**
> Pin geoh5py to 0.1.5.rc1

- environment.yml
**GEOPY-332 - Release geoapps 0.6.0**
> GEOPY-332: Dependencies

- .github/workflows/pr_add_jira_summary.yml
to test, create a PR targeting this branch with some comment like:
so let's see if this comment passes! Seems a good test with something "special" characters *@ and {{more}}
> GEOPY-407: add_jira_summary pipeline is failing on github

- .github/workflows/pytest-windows.yaml
- environment.yml
**GEOPY-417 - Octree App: Mesh always written to FlinFlon.geoh5 **
> Geopy 417test

- Install_or_Update.bat
- Start_applications.bat
- get_conda_exec.bat
**GEOPY-481 - Conflict with geosoft as default anaconda**
> GEOPY-481: fixup - protect against space in path

- geoapps/inversion/driver.py
GEOPY-541: Avoid double run of the forward
> GEOPY-541: Avoid double run of forward

- devtools/start-app.bat
**GEOPY-358 - use local editable geoh5py in geoapps dev environment**
> GEOPY-358: fix start-app in dev environment

- docs/conf.py
- geoapps/__init__.py
- pyproject.toml
**GEOPY-622 - Release geoapps 0.8.1**
> GEOPY-622 remove beta from version

- .github/dependabot.yml
for actions, scheduled monthly
> Configure dependabot version update

- docs/conf.py
- geoapps/__init__.py
- pyproject.toml
**GEOPY-683 - geoapps 0.9.0-rc.2 version**
> GEOPY-683: set version to rc.2

- .pre-commit-config.yaml
**GEOPY-686 - autoupdate precommit hooks monthly on devlop branch**
> GEOPY-686: autoupdate pre-commit hooks on develop branch monthly

- .github/workflows/create_env_file.yml
- .github/workflows/pytest-windows.yaml
- .github/workflows/static-analysis.yml
- Install_or_Update.bat
- devtools/create_application_env_files.py
- devtools/run_conda_lock.py
- devtools/setup-dev.bat
**GEOPY-682 - geoapps 0.9.0 yml file for analyst simpeg fails to install**
> GEOPY-683: use Python 3.10 for installation

- devtools/create_application_env_files.py
**GEOPY-680 - error in github action creating distribution env file**
> GEOPY-680: fixup generation of app env file

- .pre-commit-config.yaml
- docs/conf.py
- geoapps/__init__.py
- geoapps/inversion/components/data.py
- geoapps/inversion/components/factories/entity_factory.py
- pyproject.toml
- tests/run_tests/driver_mvi_test.py
**GEOPY-693 - release of 0.9.0**
> GEOPY-693: merge release/0.9.0 to main

- geoapps/driver_base/driver.py
- tests/run_tests/octree_creation_test.py
- tests/run_tests/peak_finder_test.py
**GEOPY-732 - Workspace closed on ui.json execution of non-inversion apps**
> GEOPY-732: Workspace closed on ui.json execution of non-inversion apps

- get_conda_exec.bat
**GEOPY-828 - new installation location for latest miniconda version**
> GEOPY-828: new installation location for latest miniconda version

- tests/__init__.py
**GEOPY-829 - unit test failure on 0.9.2 and develop branches**
(cherry picked from commit 690e0c3852934cf35c9fbe77ade47c62c0c68832)
> GEOPY-829: unit test failure on 0.9.2 and develop branches

- Install_or_Update.bat
- devtools/setup-conda-base.bat
- devtools/setup-dev.bat
**GEOPY-734 - error not finding SSL when installing geoapps**
[GEOPY-734]: https://mirageoscience.atlassian.net/browse/GEOPY-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GEOPY-734: error not finding SSL when installing geoapps

- docs/conf.py
- geoapps/__init__.py
- pyproject.toml
**GEOPY-825 - Release geoapps-0.9.2**
> GEOPY-825: set version to 0.9.2-beta

- Install_or_Update.bat
- Start_applications.bat
- devtools/run_conda_lock.bat
- devtools/setup-conda-base.bat
- devtools/setup-dev.bat
- devtools/start-app.bat
**GEOPY-828 - new installation location for latest miniconda version**
> GEOPY-828: pause before exit to show error when conda not found

- geoapps/utils/models.py
- tests/utils_test.py
**GEOPY-727 - Detection of disconnected air cells don't trigger on 2D meshes**
> GEOPY-727: Detection of disconnected air cells don't trigger on 2D meshes

- .github/workflows/create_env_file.yml
**GEOPY-833 - do not upload yml file as asset of the release**
as it is not fully functional
> GEOPY-833: do not expose the full environment

- devtools/setup-dev.bat
**GEOPY-854 - use local checkout of param-sweeps in dev environment**
> GEOPY-854: use local copy param-sweeps in dev if present

- devtools/add_url_tag_sha256.py
- devtools/create_application_env_files.py
- devtools/run_conda_lock.py
**GEOPY-866 - locked env yml contains has for pip package that make the installation fail**
> GEOPY-866: locked env yml contains hash for pip package that make the installation fail

- Install_or_Update.bat
- Start_applications.bat
- devtools/conda_env_pylint.bat
- devtools/run_conda_lock.bat
- devtools/setup-conda-base.bat
- devtools/setup-dev.bat
- devtools/start-app.bat
**GEOPY-883 - conda not found at install time**
> GEOPY-883: more robust dev, install and run scripts

- Install_or_Update.bat
- devtools/create_application_env_files.py
- devtools/setup-dev.bat
**GEOPY-895 - at installation, pip adds dependencies that are already installed by Conda**
> GEOPY-895: fix installation, when pip adds dependencies that are already installed by Conda

- devtools/add_url_tag_sha256.py
- devtools/create_application_env_files.py
**GEOPY-907 - generate locked environment file for geoapps using pypi**
> GEOPY-907: generate locked environment file for geoapps using pypi

- Start_applications.bat
**GEOPY-912 - start_notebook script not found in some instances**
> GEOPY-912: output Jupyter log to the console

- docs/content/installation.rst
**GEOPY-924 - remove reference to anaconda or miniconda**
> GEOPY-924: remove reference to anaconda or miniconda from the doc

- geoapps/utils/models.py
- tests/run_tests/driver_dc_2d_test.py
- tests/run_tests/driver_dc_p3d_test.py
- tests/run_tests/driver_ip_2d_test.py
- tests/run_tests/driver_ip_p3d_test.py
**GEOPY-934 - Mesh missed placed for non-straight dc lines**
> GEOPY-934: Mesh missed placed for non-straight dc lines

- readthedocs.yml
**GEOPY-944 - geoapps doc does not build anymore on readthedoc**
> GEOPY-944: Fix readthedocs

- .pre-commit-config.yaml
- devtools/add_url_tag_sha256.py
- devtools/create_application_env_files.py
- devtools/run_conda_lock.py
**GEOPY-948 - run_conda_lock: make it easy to skip rebuild of multi-plaform lock files**
> GEOPY-948:  run_conda_lock: make it easy to skip rebuild of multi-plaform lock files

- geoapps/inversion/components/models.py
- geoapps/inversion/joint/joint_cross_gradient/driver.py
- geoapps/inversion/joint/joint_cross_gradient/params.py
- geoapps/inversion/joint/joint_surveys/driver.py
- tests/run_tests/driver_joint_cross_gradient_test.py
**GEOPY-1005 - Fix joint cross-gradient with conductivity**
> GEOPY-1005

- geoapps/inversion/components/data.py
- geoapps/inversion/components/models.py
- geoapps/inversion/driver.py
- geoapps/inversion/joint/joint_cross_gradient/driver.py
- tests/data_test.py
- tests/models_test.py
- tests/run_tests/driver_grav_test.py
**GEOPY-1020 - Update metadata of inversions to point to new entities. **
> GEOPY-1020

- .github/workflows/create_env_file.yml
- .github/workflows/pytest-unix-os.yaml
- .github/workflows/static-analysis.yml
**GEOPY-1058 - update GitHub pipeline to use action setup-micromamba (provision-with-micromamba is deprecated)**
> GEOPY-1058 migrate to setup-micromamba in github workflows

- .github/workflows/pytest-unix-os.yaml
- .github/workflows/static-analysis.yml
**GEOPY-1083 - github action to run pylint on ubuntu**
> GEOPY-1083 run pylint on ubuntu

- .github/workflows/pytest-unix-os.yaml
- docs/conf.py
- docs/content/applications/base_application.ipynb
- docs/content/applications/clustering.ipynb
- docs/content/applications/create_block_model.ipynb
- docs/content/applications/create_isosurface.ipynb
- docs/content/applications/create_octree.ipynb
- docs/content/applications/dcip_inversion.ipynb
- docs/content/applications/edge_detection.ipynb
- docs/content/applications/grav_mag_inversion.ipynb
- docs/content/applications/peak_finder.ipynb
- docs/content/release_notes.rst
- docs/environment.yml
- geoapps/__init__.py
- pyproject.toml
**GEOPY-1023 - Prepare release geoapps-0.11.0**
> GEOPY-1023

- geoapps/driver_base/driver.py
- geoapps/inversion/joint/joint_cross_gradient/constants.py
- geoapps/inversion/joint/joint_surveys/constants.py
**GEOPY-1205 - Inversion crash on missing "version"**
> GEOPY-1205: Avoid crash on None

- geoapps/inversion/params.py
**GEOPY-1206 - Ignore out_group from selected SimPEGGroup**
> GEOPY-1206: Remove out_group assignement

- conda-py-3.10-lock.yml
- conda-py-3.9-lock.yml
- devtools/run_conda_lock.py
- devtools/setup-conda-base.bat
- environments/conda-py-3.10-linux-64-dev.lock.yml
- environments/conda-py-3.10-linux-64.lock.yml
- environments/conda-py-3.10-osx-64-dev.lock.yml
- environments/conda-py-3.10-osx-64.lock.yml
- environments/conda-py-3.10-win-64-dev.lock.yml
- environments/conda-py-3.10-win-64.lock.yml
- environments/conda-py-3.9-linux-64-dev.lock.yml
- environments/conda-py-3.9-linux-64.lock.yml
- environments/conda-py-3.9-osx-64-dev.lock.yml
- environments/conda-py-3.9-osx-64.lock.yml
- environments/conda-py-3.9-win-64-dev.lock.yml
- environments/conda-py-3.9-win-64.lock.yml
- pyproject.toml
**GEOPY-1232 - conda-lock is marking some non-optional packages as optional**
> GEOPY-1232: fix non-optional dependencies in conda lock file

- geoapps/inversion/components/models.py
- geoapps/inversion/joint/driver.py
**GEOPY-1265 - Log bounds applied to twice on joint inversion**
> Geopy 1265 minimal

- geoapps/inversion/components/factories/source_factory.py
- pyproject.toml
- tests/run_tests/driver_mag_test.py
**GEOPY-1325 - Magnetic field amplitude strength not passed to survey.source**
> GEOPY-1325

- geoapps/inversion/components/models.py
- geoapps/inversion/joint/joint_surveys/driver.py
**GEOPY-1265 - Log bounds applied to twice on joint inversion**
> GEOPY-1265

- geoapps/inversion/components/data.py
**GEOPY-1409 - Pseudo 2D inversion crash on hanging line_id field**
> GEOPY-1409

- geoapps/contours/constants.py
- geoapps/edge_detection/application.py
**GEOPY-1427 - Crash on start of jupyter-app with worspace input. **
> GEOPY-1427

- geoapps/inversion/base_inversion_application.py
**GEOPY-1471 - Inversion app fails on gravity**
> GEOPY-1471: Inversion app fails on gravity

- geoapps/block_model_creation/application.py
- geoapps/contours/application.py
- geoapps/edge_detection/application.py
- geoapps/index.ipynb
- geoapps/interpolation/application.py
- geoapps/inversion/base_inversion_application.py
- geoapps/inversion/electricals/application.py
- geoapps/inversion/potential_fields/application.py
- geoapps/inversion/potential_fields/gravity/application.py
- geoapps/inversion/potential_fields/magnetic_scalar/application.py
- geoapps/inversion/potential_fields/magnetic_vector/application.py
- geoapps/iso_surfaces/application.py
- geoapps/octree_creation/application.py
- geoapps/octree_creation/notebook.ipynb
- geoapps/peak_finder/application.py
**GEOPY-1493 - Validation crash when setting the target geoh5 in jupyter app**
> GEOPY-1493: Validation crash when setting the target geoh5 in jupyter app

- geoapps/block_model_creation/constants.py
- geoapps/calculator/application.py
- geoapps/clustering/constants.py
- geoapps/contours/constants.py
- geoapps/coordinate_transformation/application.py
- geoapps/edge_detection/constants.py
- geoapps/export/application.py
- geoapps/interpolation/constants.py
- geoapps/inversion/electromagnetics/application.py
- geoapps/octree_creation/notebook.ipynb
- geoapps/scatter_plot/constants.py
**GEOPY-1502 - Exception for missing association not handled by contouring app**
> GEOPY-1502: Exception for missing association not handled by contouring app

- environments/py-3.10-linux-64-dev.conda.lock.yml
- environments/py-3.10-linux-64.conda.lock.yml
- environments/py-3.10-win-64-dev.conda.lock.yml
- environments/py-3.10-win-64.conda.lock.yml
- py-3.10.conda-lock.yml
**GEOPY-1523 - make geoapps use latest simpeg version**
> GEOPY-1523: update conda lock files

- geoapps/octree_creation/constants.py
**GEOPY-1461 - Update jupyter-app to match latest on octree-creation-app**
> GEOPY-1461: Update jupyter-app to match latest on octree-creation-app

- geoapps/contours/application.py
- geoapps/edge_detection/application.py
**GEOPY-1570 - Displayed edges in the preview should only be within the window area**
> GEOPY-1570: Displayed edges in the preview should only be within the window area

- geoapps/base/dash_application.py
- geoapps/block_model_creation/application.py
- geoapps/clustering/application.py
- geoapps/inversion/base_inversion_application.py
- geoapps/scatter_plot/application.py
**GEOPY-1598 - Remove CSS from dash app template**
> GEOPY-1598: Remove CSS from dash app template

- docs/conf.py
- geoapps/__init__.py
- pyproject.toml
**GEOPY-1651 - Release packages for Analyst 4.4.1**
> GEOPY-1651: use updated simpeg-drivers and param-sweeps

- environments/py-3.10-linux-64-dev.conda.lock.yml
- environments/py-3.10-linux-64.conda.lock.yml
- environments/py-3.10-win-64-dev.conda.lock.yml
- environments/py-3.10-win-64.conda.lock.yml
- py-3.10.conda-lock.yml
- pyproject.toml
**GEOPY-1692 - merge updated geoapps "0.12 dev" to develop**
> GEOPY-1692: merge updated geoapps "0.12 dev" to develop

- .github/workflows/pr_add_jira_summary.yml
- .github/workflows/python_analysis.yml
Uses https://github.com/MiraGeoscience/CI-tools/pull/23
> Devops 471

- .github/workflows/issue_to_jira.yml
**DEVOPS-654 - broken automation creating JIRA issue from GitHub issue**
> DEVOPS-654: jira issue component

- README.rst
- docs/environment.yml
**GEOPY-1163 - update the readme of geoapps**
> GEOPY-1163: update the readme of geoapps
